# Generated by Django 4.1.4 on 2023-11-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passport',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
