# Generated by Django 4.2.7 on 2023-12-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointissue',
            name='corpus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='corpus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Корпус'),
        ),
    ]
