# Generated by Django 4.2.7 on 2023-11-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_remove_role_salary_alter_car_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
