# Generated by Django 4.1.4 on 2023-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_alter_customuser_date_of_birth_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
    ]
