# Generated by Django 4.2.7 on 2023-12-01 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_alter_pointissue_corpus_alter_warehouse_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_of_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки в пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='pointissue',
            name='warehouse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.warehouse', verbose_name='Cклад'),
        ),
    ]
