# Generated by Django 4.2.7 on 2023-12-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_alter_car_driver_id_alter_package_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='date_of_receipt',
            field=models.DateField(verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота(м)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина(м)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес(кг)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина(м)'),
        ),
    ]
