# Generated by Django 4.1.4 on 2023-11-29 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driver_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'post__name': 'Сотрудник'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Id водителя'),
        ),
    ]
