# Generated by Django 4.2.7 on 2023-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passport',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Серия номер паспорта'),
        ),
    ]
