# Generated by Django 4.2.7 on 2023-12-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_alter_package_date_of_receipt_alter_package_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машину', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='cargocategory',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Посылку', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterModelOptions(
            name='pointissue',
            options={'verbose_name': 'Пункт выдачи', 'verbose_name_plural': 'Пункты выдачи'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
    ]
